services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gs-task-app
    container_name: gs-task-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - gs-task-network

  webserver:
    image: nginx:alpine
    container_name: gs-task-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - gs-task-network
    depends_on:
      - app

networks:
  gs-task-network:
    driver: bridge
